### ISSUE TITLE
Update Gridsome Plugin Page Example

### ISSUE THREAD

**Issue by NickStees** [frndcolin/gridsome-plugin-sentry#1]
The example on the [Gridsome website ](https://gridsome.org/plugins/gridsome-plugin-sentry) has options.url while the Github readme is options.dsn and the latter opitons.dsn seems to be correct. 

```
options: {
        url: ....
```

**Comment by frndcolin** [comment]
forgot to re-publish to npm. 'dsn' is the right field name and the demo is that same at each package site. thanks
