### ISSUE TITLE
Don't install in development mode

### ISSUE THREAD

**Issue by thetre97** [frndcolin/gridsome-plugin-sentry#2]
Thanks for this plugin - very useful. 
However, I find it always catches errors when i'm developing a site. Wondered if it might be a good idea to add an option in the plugin config to disable sentry during dev mode?

I'd be happy to make a PR, if you would be happy with this idea.

**Comment by frndcolin** [comment]
You can silence inbound events from your Sentry dashboard, Settings -> Projects -> 'project name' -> Inbound FIlters. You can filter localhost or by IP.  Also, still feel free to create a PR if that doesn't solve the problem you are having.

**Comment by frndcolin** [comment]
I'm going to close this issue. I think @justrhysism addition of the logErrors option and the inbound filters available through Sentry will accomplish what you are looking for.

**Comment by thetre97** [comment]
Thanks @frndcolin  - I'll check out the filters
