### ISSUE TITLE
Expose `logErrors` Sentry option

### ISSUE THREAD

**Issue by justrhysism** [frndcolin/gridsome-plugin-sentry#3]
This could potentially address #2, as enabling `logErrors` in development mode would prevent errors from being swallowed.

Sentry docs: https://docs.sentry.io/platforms/javascript/vue/

**Comment by frndcolin** [comment]
Thanks for bringing attention to this. I am not sure if this will solve #2, I replied there as well if you were also having the same issue. I'll add this option in this weekend, or if you want to add a PR feel free.

**Comment by justrhysism** [comment]
With respect to #2, it won't disable the plugin; however, I think the primary cause for concern for @thetre97 was being unable to see the errors during development.

Setting `logErrors: process.env.NODE_ENV` in the plugin config will address this issue.
