### ISSUE TITLE
async deffered loading

### ISSUE THREAD

**Issue by milindsingh** [frndcolin/gridsome-plugin-sentry#5]
Hi, Thanks for creating this plugin for gridsome.

I am searching for optimization in sentry bundle loading in gridsome, any suggestion on how we can load async deffer sentry js unblocking the gridsome?

**Comment by frndcolin** [comment]
This is an interesting idea. I have unfortunately been away from gridsome and sentry for a while now and not familiar with either package  to deffer loading. Using an the html tag example https://docs.sentry.io/platforms/javascript/guides/vue/ may be loaded differently or allow to add attributes on the script tag to deffer loading.
